openapi: 3.0.0
info:
  title: Shopper Ave API
  description: Shopper Ave - An E-Commerce API with MERN stack
  version: 1.0.0

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Local Development version
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
  # - url: https://example.com/api/v1
  #   description: Main (Production) server

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /signup:
    post:
      tags:
        - Authentication
      summary: Creates new user and returns the token and user information
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  default: John Doe
                email:
                  type: string
                  default: john@example.com
                password:
                  type: string
                  default: john@123
                photo:
                  type: string
                  format: binary
              required:
                - name
                - email
                - password
      responses:
        '201': 
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  token:
                    type: string
                    default: <token>
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                        default: John Doe
                      email:
                        type: string
                        default: john@example.com
                      password:
                        type: string
                        default: <password_hash>
                      role:
                        type: string
                        default: user
                      _id:
                        type: string # MongoDB internal
                        default: 54759eb3c090d83494e2d804
                      createdAt:
                        type: string
                        default:  2022-09-26T05:53:07.739Z
                      updatedAt:
                        type: string
                        default: 2022-09-26T05:53:07.739Z
                      __v:
                        type: number # Mongoose internal
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  err:
                    type: string
                    default: Name, email and password are required
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  err:
                    type: string
                    default: Something went wrong!
