name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Turborepo Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
    
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Run test
        run: yarn test

      - name: Generate server coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
            package-manager: yarn
            working-directory: apps/server
            output: report-markdown
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
            message: ${{ steps.coverage.outputs.report }}
