name: CI Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
    
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
